# Find the header files

FIND_PATH(G2O_INCLUDE_DIR g2o/core/base_vertex.h
  ${G2O_ROOT}/include
  $ENV{G2O_ROOT}/include
  $ENV{G2O_ROOT}
  /usr/local/include
  /usr/include
  /opt/local/include
  /sw/local/include
  /sw/include
  NO_DEFAULT_PATH
  )

# Macro to unify finding both the debug and release versions of the
# libraries; this is adapted from the OpenSceneGraph FIND_LIBRARY
# macro.

MACRO(FIND_G2O_LIBRARY MYLIBRARY MYLIBRARYNAME)

  FIND_LIBRARY("${MYLIBRARY}_DEBUG"
    NAMES "g2o_${MYLIBRARYNAME}_d"
    PATHS
    ${G2O_ROOT}/lib/Debug
    ${G2O_ROOT}/lib
    $ENV{G2O_ROOT}/lib/Debug
    $ENV{G2O_ROOT}/lib
    NO_DEFAULT_PATH
    )

  FIND_LIBRARY("${MYLIBRARY}_DEBUG"
    NAMES "g2o_${MYLIBRARYNAME}_d"
    PATHS
    ~/Library/Frameworks
    /Library/Frameworks
    /usr/local/lib
    /usr/local/lib64
    /usr/lib
    /usr/lib64
    /opt/local/lib
    /sw/local/lib
    /sw/lib
    )
  
  FIND_LIBRARY(${MYLIBRARY}
    NAMES "g2o_${MYLIBRARYNAME}"
    PATHS
    ${G2O_ROOT}/lib/Release
    ${G2O_ROOT}/lib
    $ENV{G2O_ROOT}/lib/Release
    $ENV{G2O_ROOT}/lib
    NO_DEFAULT_PATH
    )

  FIND_LIBRARY(${MYLIBRARY}
    NAMES "g2o_${MYLIBRARYNAME}"
    PATHS
    ~/Library/Frameworks
    /Library/Frameworks
    /usr/local/lib
    /usr/local/lib64
    /usr/lib
    /usr/lib64
    /opt/local/lib
    /sw/local/lib
    /sw/lib
    )
  
  IF(NOT ${MYLIBRARY}_DEBUG)
    IF(MYLIBRARY)
      SET(${MYLIBRARY}_DEBUG ${MYLIBRARY})
    ENDIF(MYLIBRARY)
  ENDIF( NOT ${MYLIBRARY}_DEBUG)
  
ENDMACRO(FIND_G2O_LIBRARY LIBRARY LIBRARYNAME)

# Find the core elements
FIND_G2O_LIBRARY(G2O_STUFF_LIBRARY stuff)
IF (G2O_STUFF_LIBRARY_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_STUFF_LIBRARY_DEBUG})
ENDIF (G2O_STUFF_LIBRARY_DEBUG)
IF (G2O_STUFF_LIBRARY)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_STUFF_LIBRARY})
ENDIF (G2O_STUFF_LIBRARY)

FIND_G2O_LIBRARY(G2O_CORE_LIBRARY core)
IF (G2O_CORE_LIBRARY_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_CORE_LIBRARY_DEBUG})
ENDIF (G2O_CORE_LIBRARY_DEBUG)
IF (G2O_CORE_LIBRARY)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_CORE_LIBRARY})
ENDIF (G2O_CORE_LIBRARY)

# Find the CLI library
FIND_G2O_LIBRARY(G2O_CLI_LIBRARY cli)
IF (G2O_CLI_LIBRARY_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_CLI_LIBRARY_DEBUG})
ENDIF (G2O_CLI_LIBRARY_DEBUG)
IF (G2O_CLI_LIBRARY)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_CLI_LIBRARY})
ENDIF (G2O_CLI_LIBRARY)

# Find the pluggable solvers
FIND_G2O_LIBRARY(G2O_SOLVER_CHOLMOD solver_cholmod)
IF (G2O_SOLVER_CHOLMOD_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_CHOLMOD_DEBUG})
ENDIF (G2O_SOLVER_CHOLMOD_DEBUG)
IF (G2O_SOLVER_CHOLMOD)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_CHOLMOD})
ENDIF (G2O_SOLVER_CHOLMOD)

FIND_G2O_LIBRARY(G2O_SOLVER_CSPARSE solver_csparse)
IF (G2O_SOLVER_CSPARSE_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_CSPARSE_DEBUG})
ENDIF (G2O_SOLVER_CSPARSE_DEBUG)
IF (G2O_SOLVER_CSPARSE)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_CSPARSE})
ENDIF (G2O_SOLVER_CSPARSE)

FIND_G2O_LIBRARY(G2O_SOLVER_CSPARSE_EXTENSION csparse_extension)
IF (G2O_SOLVER_CSPARSE_EXTENSION_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_CSPARSE_EXTENSION_DEBUG})
ENDIF (G2O_SOLVER_CSPARSE_EXTENSION_DEBUG)
IF (G2O_SOLVER_CSPARSE_EXTENSION)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_CSPARSE_EXTENSION})
ENDIF (G2O_SOLVER_CSPARSE_EXTENSION)

FIND_G2O_LIBRARY(G2O_SOLVER_DENSE solver_dense)
IF (G2O_SOLVER_DENSE_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_DENSE_DEBUG})
ENDIF (G2O_SOLVER_DENSE_DEBUG)
IF (G2O_SOLVER_DENSE)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_DENSE})
ENDIF (G2O_SOLVER_DENSE)

FIND_G2O_LIBRARY(G2O_SOLVER_PCG solver_pcg)
IF (G2O_SOLVER_PCG_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_PCG_DEBUG})
ENDIF (G2O_SOLVER_PCG_DEBUG)
IF (G2O_SOLVER_PCG)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_PCG})
ENDIF (G2O_SOLVER_PCG)

FIND_G2O_LIBRARY(G2O_SOLVER_SLAM2D_LINEAR solver_slam2d_linear)
IF (G2O_SOLVER_SLAM2D_LINEAR_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_SLAM2D_LINEAR_DEBUG})
ENDIF (G2O_SOLVER_SLAM2D_LINEAR_DEBUG)
IF (G2O_SOLVER_SLAM2D_LINEAR)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_SLAM2D_LINEAR})
ENDIF (G2O_SOLVER_SLAM2D_LINEAR)

FIND_G2O_LIBRARY(G2O_SOLVER_STRUCTURE_ONLY solver_structure_only)
IF (G2O_SOLVER_STRUCTURE_ONLY_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_STRUCTURE_ONLY_DEBUG})
ENDIF (G2O_SOLVER_STRUCTURE_ONLY_DEBUG)
IF (G2O_SOLVER_STRUCTURE_ONLY)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_STRUCTURE_ONLY})
ENDIF (G2O_SOLVER_STRUCTURE_ONLY)

FIND_G2O_LIBRARY(G2O_SOLVER_EIGEN solver_eigen)
IF (G2O_SOLVER_EIGEN_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_SOLVER_EIGEN_DEBUG})
ENDIF (G2O_SOLVER_EIGEN_DEBUG)
IF (G2O_SOLVER_EIGEN)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_SOLVER_EIGEN})
ENDIF (G2O_SOLVER_EIGEN)


# Find the predefined types
FIND_G2O_LIBRARY(G2O_TYPES_DATA types_data)
IF (G2O_TYPES_DATA_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_DATA_DEBUG})
ENDIF (G2O_TYPES_DATA_DEBUG)
IF (G2O_TYPES_DATA)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_DATA})
ENDIF (G2O_TYPES_DATA)

FIND_G2O_LIBRARY(G2O_TYPES_ICP types_icp)
IF (G2O_TYPES_ICP_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_ICP_DEBUG})
ENDIF (G2O_TYPES_ICP_DEBUG)
IF (G2O_TYPES_ICP)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_ICP})
ENDIF (G2O_TYPES_ICP)

FIND_G2O_LIBRARY(G2O_TYPES_SBA types_sba)
IF (G2O_TYPES_SBA_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_SBA_DEBUG})
ENDIF (G2O_TYPES_SBA_DEBUG)
IF (G2O_TYPES_SBA)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_SBA})
ENDIF (G2O_TYPES_SBA)

FIND_G2O_LIBRARY(G2O_TYPES_SCLAM2D types_sclam2d)
IF (G2O_TYPES_SCLAM2D_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_SCLAM2D_DEBUG})
ENDIF (G2O_TYPES_SCLAM2D_DEBUG)
IF (G2O_TYPES_SCLAM2D)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_SCLAM2D})
ENDIF (G2O_TYPES_SCLAM2D)

FIND_G2O_LIBRARY(G2O_TYPES_SIM3 types_sim3)
IF (G2O_TYPES_SIM3_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_SIM3_DEBUG})
ENDIF (G2O_TYPES_SIM3_DEBUG)
IF (G2O_TYPES_SIM3)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_SIM3})
ENDIF (G2O_TYPES_SIM3)

FIND_G2O_LIBRARY(G2O_TYPES_SLAM2D types_slam2d)
IF (G2O_TYPES_SLAM2D_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_SLAM2D_DEBUG})
ENDIF (G2O_TYPES_SLAM2D_DEBUG)
IF (G2O_TYPES_SLAM2D)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_SLAM2D})
ENDIF (G2O_TYPES_SLAM2D)

FIND_G2O_LIBRARY(G2O_TYPES_SLAM3D types_slam3d)
IF (G2O_TYPES_SLAM3D_DEBUG)
  LIST(APPEND G2O_LIBRARIES_DEBUG debug ${G2O_TYPES_SLAM3D_DEBUG})
ENDIF (G2O_TYPES_SLAM3D_DEBUG)
IF (G2O_TYPES_SLAM3D)
  LIST(APPEND G2O_LIBRARIES optimized ${G2O_TYPES_SLAM3D})
ENDIF (G2O_TYPES_SLAM3D)

LIST(APPEND G2O_LIBRARIES ${G2O_LIBRARIES_DEBUG})

# G2O solvers declared found if we found at least one solver
SET(G2O_SOLVERS_FOUND "NO")
IF(G2O_SOLVER_CHOLMOD OR G2O_SOLVER_CSPARSE OR G2O_SOLVER_DENSE OR G2O_SOLVER_PCG OR G2O_SOLVER_SLAM2D_LINEAR OR G2O_SOLVER_STRUCTURE_ONLY OR G2O_SOLVER_EIGEN)
  SET(G2O_SOLVERS_FOUND "YES")
ENDIF(G2O_SOLVER_CHOLMOD OR G2O_SOLVER_CSPARSE OR G2O_SOLVER_DENSE OR G2O_SOLVER_PCG OR G2O_SOLVER_SLAM2D_LINEAR OR G2O_SOLVER_STRUCTURE_ONLY OR G2O_SOLVER_EIGEN)

# G2O itself declared found if we found the core libraries and at least one solver
SET(G2O_FOUND "NO")
IF(G2O_STUFF_LIBRARY AND G2O_CORE_LIBRARY AND G2O_INCLUDE_DIR AND G2O_SOLVERS_FOUND)
  SET(G2O_FOUND "YES")
ENDIF(G2O_STUFF_LIBRARY AND G2O_CORE_LIBRARY AND G2O_INCLUDE_DIR AND G2O_SOLVERS_FOUND)
